name: HitmanPlugin
version: 1.0
main: io.github.devnull03.HitmanPlugin
api-version: 1.16
authors: [ devnull03 ]
description: plugin similar to the 3 hitmen dream video
commands:
  hitman:
    usage: /hitman <command>
